---
title: "Functional Group Models"
author: "Maggie Klope"
date: "1/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(stats)
library(sjPlot)
library(FD)
library(DHARMa) #model diagnostics
library(glmmTMB) #model fitting
library(MuMIn) #model summaries and comparisons
library(emmeans) #post-hoc analyses
library(gt)
library(tibble)
library(lsmeans)
library(gridExtra)
library(multcomp)
library(car)
library(ggeffects)

other_traits <- read_csv("~/github/Tejon_Functional_Traits/Datasheets/seed_mass_leaf_N.csv")

cwm_traits_adj <-  read_csv("~/github/Tejon_Functional_Traits/Datasheets/cwm_traits_updated.csv") %>% 
  left_join(other_traits, by = "species_name") %>% 
  mutate(weighted_la = leaf_area * Abundance) %>% #multiplying trait values by species abundance
  mutate(weighted_sla = sla * Abundance) %>% 
  mutate(weighted_ldmc = ldmc * Abundance) %>%
  mutate(weighted_seed_mass = seed_mass * Abundance) %>%
  mutate(weighted_n = leaf_n * Abundance) %>%
  group_by(climate, treatment, Block) %>% #grouping by climate, treatment, and block
  summarise_all(mean, na.rm = TRUE) %>% #finding the mean
  dplyr::select(climate, treatment, Block, weighted_la, weighted_sla, weighted_ldmc, weighted_seed_mass, weighted_n)

# log transformation for seed mass & leaf n
cwm_traits_adj <- cwm_traits_adj %>% 
  mutate(log_seed_mass = log(weighted_seed_mass)) %>% 
  mutate(log_n = log(weighted_n))

```

```{r, include=FALSE}
cwm_functional <-  read_csv("~/github/Tejon_Functional_Traits/Datasheets/cwm_traits_updated.csv") %>%
  left_join(other_traits, by = "species_name") %>% 
  mutate(weighted_la = leaf_area * Abundance) %>% #multiplying trait values by species abundance
  mutate(weighted_sla = sla * Abundance) %>% 
  mutate(weighted_ldmc = ldmc * Abundance) %>%
  mutate(weighted_seed_mass = seed_mass * Abundance) %>%
  mutate(weighted_n = leaf_n * Abundance) %>%
  group_by(climate, treatment, Block, functional_group) %>% #grouping by climate, treatment, and block
  summarise_all(mean, na.rm = TRUE) %>% #finding the mean
  dplyr::select(climate, treatment, functional_group, weighted_la, weighted_sla, weighted_ldmc, weighted_seed_mass, weighted_n)

cwm_functional_2 <- read_csv("~/github/Tejon_Functional_Traits/Datasheets/cwm_traits_updated.csv") %>% 
  left_join(other_traits, by = "species_name") %>% 
  dplyr::select(climate, treatment, Block, functional_group, Abundance) %>% 
  dplyr::filter(Block == "A" | Block ==  "D" | Block ==  "G") %>% 
  group_by(climate, functional_group) %>% 
  summarise(Total_Abundance = sum(Abundance))

ggplot(cwm_functional_2, aes(x = "", y = Total_Abundance, fill = functional_group)) +
  geom_bar(stat="identity", width=1, color = "white") +
  coord_polar("y", start = 0) +
  facet_wrap(~climate) +
  theme_void() +
  labs(fill = "Functional Group:") +
  scale_fill_manual(values = c("#c7eae5", "#b8e186", "#dfc27d")) +
  theme(plot.background = element_rect(fill = "transparent", color = NA),
        legend.background = element_rect(fill = "white", size = 0)) +
  theme(legend.position="bottom")
  
# ggsave("plant_communit_piechart.png", path = "~/github/Tejon_Functional_Traits/Figures", width = 9, height = 7, bg = "transparent")

#  barplot showing all climate/treatments
cwm_functional %>%
  pivot_longer(cols = weighted_la:weighted_n,
               names_to = "traits",
               values_to = "value") %>%
  ggplot(aes(x = climate, y = value, color = treatment)) +
  geom_boxplot() +
  theme_bw() +
  facet_grid(traits ~ functional_group, scales = "free")

# ggsave("cwm_by_functional_group_barchart.png", path = "~/github/Tejon_Functional_Traits/Figures", width = 9, height = 7, bg = "transparent")

# grass <- cwm_functional %>% 
#   filter(functional_group == "grass")
# 
# forb <- cwm_functional %>% 
#   filter(functional_group == "forb") %>% 
#   mutate(sqrt_la = sqrt(weighted_la))
# 
# shrub <- cwm_functional %>% 
#   filter(functional_group == "shrub")
  
```

#### CWMs with interaction between climate, treatment, and functional group

##### 1. leaf area
```{r}
#leaf area is very skewed:
ggplot(cwm_functional, aes(x = weighted_la)) +
  geom_histogram() +
  theme_bw()+
  facet_wrap(~functional_group)

# #trying glm
# funct_la <- glm(data = cwm_functional, weighted_la ~ climate * treatment * functional_group, family = gaussian, na.action = na.fail)
# dredge(funct_la)
# 
# simulateResiduals(funct_la, plot= T) #does not pass dispersion test
# shapiro.test(residuals(funct_la)) #but residuals are normal
# 
# testDispersion(simulateResiduals(funct_la, plot= T)) # does not pass
# 
# #trying log transformation with gaussian
# cwm_functional <- cwm_functional %>% 
#   mutate(log_la = log(weighted_la))
# 
# ggplot(cwm_functional, aes(x = log_la)) +
#   geom_histogram() +
#   theme_bw()+
#   facet_wrap(~functional_group)
# 
# funct_la <- glm(data = cwm_functional, log_la ~ climate * treatment * functional_group, family = gaussian, na.action = na.fail)
# dredge(funct_la)
# funct_la <- glm(data = cwm_functional, log_la ~ climate + treatment + functional_group + climate:functional_group + functional_group:treatment, family = gaussian, na.action = na.fail)
# 
# simulateResiduals(funct_la, plot= T) #looks good
# shapiro.test(residuals(funct_la)) # but residuals are not normal
# 
# # trying Gamma with log link on un-transformed
# funct_la <- glm(data = cwm_functional, weighted_la ~ climate * treatment * functional_group, family = Gamma(link = "log"), na.action = na.fail)
# dredge(funct_la)
# funct_la <- glm(data = cwm_functional, weighted_la ~ climate + treatment + functional_group + climate:functional_group + functional_group:treatment, family = Gamma(link = "log"), na.action = na.fail)
# 
# simulateResiduals(funct_la, plot= T) #does not pass dispersion test, but is very close!
# shapiro.test(residuals(funct_la)) #but residuals are normal

#trying log+1 with gaussian
cwm_functional <- cwm_functional %>% 
  mutate(log_plus_la = log(weighted_la + 1))

ggplot(cwm_functional, aes(x = log_plus_la)) +
  geom_histogram() +
  theme_bw()

funct_la <- glmmTMB(data = cwm_functional, log_plus_la ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_la)
funct_la <- glmmTMB(data = cwm_functional, log_plus_la ~ climate + treatment + functional_group + climate:functional_group + functional_group:treatment + (1|Block), family = gaussian, na.action = na.fail)

simulateResiduals(funct_la, plot= T) #good? Two outliers
shapiro.test(residuals(funct_la)) #residuals are normal

# pairwise comparisons
# emmeans(funct_la, pairwise ~ climate)
# emmeans(funct_la, pairwise ~ treatment)
# emmeans(funct_la, pairwise ~ functional_group)
# emmeans(funct_la, pairwise ~ treatment | functional_group)
# emmeans(funct_la, pairwise ~ climate | functional_group)

# # finding significant pairs
# LA_funct_sig_pairs <- as.data.frame(pairs(emmeans(funct_la, ~ climate * treatment * functional_group))) %>%
#   separate(contrast, c("A", "B"), sep = " - ") %>%
#   separate(A, c("A_climate", "A_treatment", "A_functional_group"), sep = ",") %>%
#   separate(B, c("B_climate", "B_treatment", "B_functional_group"), sep = ",") %>%
#   filter((A_climate == B_climate & A_functional_group == B_functional_group) |
#           (A_climate == B_climate & A_treatment == B_treatment) |
#            (A_treatment == B_treatment & A_functional_group == B_functional_group))
# LA_funct_sig_pairs

```
##### 2. specific leaf area
```{r}
#leaf area is very skewed:
ggplot(cwm_functional, aes(x = weighted_sla)) +
  geom_histogram() +
  theme_bw()+
  facet_wrap(~functional_group)

cwm_functional <- cwm_functional %>% 
  mutate(log_sla = log(weighted_sla))

# funct_sla <- glmmTMB(data = cwm_functional, weighted_sla ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
# dredge(funct_sla)
# 
# simulateResiduals(funct_sla, plot= T) #does not pass
# shapiro.test(residuals(funct_sla)) # not normal

# trying log transformation with gaussian
funct_sla <- glmmTMB(data = cwm_functional, log_sla ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_sla)
funct_sla <- glmmTMB(data = cwm_functional, log_sla ~ climate + functional_group + treatment + climate:functional_group + (1|Block), family = gaussian, na.action = na.fail)

simulateResiduals(funct_sla, plot= T) # good
shapiro.test(residuals(funct_sla)) # not normal, but does that matter??

# # trying Gamma with log link on un-transformed
# funct_sla <- glm(data = cwm_functional, weighted_sla ~ climate * treatment * functional_group, family = Gamma, na.action = na.fail)
# dredge(funct_sla)
# funct_sla <- glm(data = cwm_functional, weighted_sla ~ climate + functional_group + treatment + climate:functional_group, family = Gamma, na.action = na.fail)
# 
# simulateResiduals(funct_sla, plot= T) # not normal
# shapiro.test(residuals(funct_sla)) # not normal
# 
# #trying log+1 with gaussian
# cwm_functional <- cwm_functional %>% 
#   mutate(log_plus_sla = log(weighted_sla + 1))
# 
# funct_sla <- glm(data = cwm_functional, log_plus_sla ~ climate * treatment * functional_group, family = gaussian, na.action = na.fail)
# dredge(funct_sla)
# funct_sla <- glm(data = cwm_functional, log_plus_sla ~ climate + functional_group + treatment + climate:functional_group, family = gaussian, na.action = na.fail)
# 
# simulateResiduals(funct_sla, plot= T) #good
# shapiro.test(residuals(funct_sla)) #normal

emmeans(funct_sla, pairwise ~ functional_group)
emmeans(funct_sla, pairwise ~ climate)
emmeans(funct_sla, pairwise ~ treatment)

emmeans(funct_sla, pairwise ~ treatment | functional_group)
emmeans(funct_sla, pairwise ~ climate | functional_group)

```
##### 3. ldmc
```{r}
cwm_functional <- cwm_functional %>% 
  mutate(log_ldmc = log(weighted_ldmc))

funct_ldmc <- glmmTMB(data = cwm_functional, weighted_ldmc ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_ldmc)
funct_ldmc <- glmmTMB(data = cwm_functional, weighted_ldmc ~ climate + functional_group + treatment + climate:functional_group + functional_group:treatment + (1|Block), na.action = na.fail)

simulateResiduals(funct_ldmc, plot= T) # Not good

# log transformation
funct_ldmc <- glmmTMB(data = cwm_functional, log_ldmc ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_ldmc)
funct_ldmc <- glmmTMB(data = cwm_functional, log_ldmc ~ climate + functional_group + treatment + climate:functional_group + functional_group:treatment + (1|Block), na.action = na.fail)

simulateResiduals(funct_ldmc, plot= T) # ok
shapiro.test(residuals(funct_ldmc)) # normal

# emmeans(funct_ldmc, pairwise ~ climate)
# emmeans(funct_ldmc, pairwise ~ treatment)
# 
# emmeans(funct_ldmc, pairwise ~ treatment | functional_group)
# emmeans(funct_ldmc, pairwise ~ climate | functional_group)

```
##### 4. lnc
```{r}
funct_n <- glmmTMB(data = cwm_functional, weighted_n ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_n)
funct_n <- glmmTMB(data = cwm_functional, weighted_n ~ climate + functional_group + treatment + climate:functional_group + functional_group:treatment + (1|Block), na.action = na.fail)

simulateResiduals(funct_n, plot= T) # not good

cwm_functional <- cwm_functional %>% 
  mutate(log_n = log(weighted_n)) %>% 
  mutate(log_plus_n = log(weighted_n+1))

# trying log transformation with gaussian
funct_n <- glmmTMB(data = cwm_functional, log_n ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_n)
funct_n <- glmmTMB(data = cwm_functional, log_n ~ climate + functional_group + treatment + climate:functional_group + (1|Block), na.action = na.fail)

simulateResiduals(funct_n, plot= T) # looks good
shapiro.test(residuals(funct_n)) # not normal - is that ok?

# # trying log(n+1) transformation with gaussian
# funct_n <- glm(data = cwm_functional, log_plus_n ~ climate * treatment * functional_group, family = gaussian, na.action = na.fail)
# dredge(funct_n)
# funct_n <- glm(data = cwm_functional, log_plus_n ~ climate + functional_group + treatment + climate:functional_group, family = gaussian, na.action = na.fail)
# 
# simulateResiduals(funct_n, plot= T) # looks ok
# shapiro.test(residuals(funct_n)) # normal

# emmeans(funct_n, pairwise ~ climate)
# emmeans(funct_n, pairwise ~ treatment)

# emmeans(funct_n, pairwise ~ treatment | functional_group)
# emmeans(funct_n, pairwise ~ climate | functional_group)

```
##### 5. seed mass
```{r}
# untransformed with gaussian
funct_seed_mass <- glmmTMB(data = cwm_functional, weighted_seed_mass ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_seed_mass)
funct_seed_mass <- glmmTMB(data = cwm_functional, weighted_seed_mass ~ climate + functional_group + climate:functional_group + (1|Block), na.action = na.fail)

simulateResiduals(funct_seed_mass, plot= T) # bad

# log transformation with gaussian
cwm_functional <- cwm_functional %>% 
  mutate(log_seed_mass = log(weighted_seed_mass))

funct_seed_mass <- glmmTMB(data = cwm_functional, log_seed_mass ~ climate * treatment * functional_group + (1|Block), family = gaussian, na.action = na.fail)
dredge(funct_seed_mass)
funct_seed_mass <- glmmTMB(data = cwm_functional,log_seed_mass ~ climate + functional_group + climate:functional_group + (1|Block), na.action = na.fail)

simulateResiduals(funct_seed_mass, plot= T) # ok
shapiro.test(residuals(funct_seed_mass)) # normal

# # for back transformation
# funct_seed_mass <- glm(data = cwm_functional, log(weighted_seed_mass) ~ climate + functional_group + climate:functional_group, na.action = na.fail)
# emmeans::contrast(funct_seed_mass)
# 
# funct_seed_mass_emm <- emmeans(funct_seed_mass, ~ climate + functional_group + climate:functional_group)
# summary(funct_seed_mass_emm) # results are given on a log scale
# summary(funct_seed_mass_emm, infer = TRUE, null = log(35), type = "response")
# 
# emmeans(funct_seed_mass, ~ climate)
# test_emm <- emmeans(funct_seed_mass, "climate", transform = "log", type = "response")
# 
# funct_seed_mass.rg <- update(ref_grid(funct_seed_mass), tran = make.tran("genlog", 1))
# 
# contrast(regrid(funct_seed_mass.rg))
# contrast(funct_seed_mass_emm)
# contrast(test_emm)
# 
# emmeans(funct_seed_mass.rg, pairwise ~ climate | functional_group)
# emmeans(funct_seed_mass, pairwise ~ climate | functional_group)
# emmeans(funct_seed_mass, pairwise ~ climate | functional_group)
# emmeans(funct_seed_mass, pairwise ~ functional_group)

```

#### Best-Fit Model Table
```{r}
dredge_funct_la <- as.data.frame(dredge(funct_la)) %>%
  filter(AICc == min(AICc)) %>%
  mutate(CWM = "log(Leaf Area + 1)") %>%
  dplyr::select(CWM, "cond(climate)", "cond(functional_group)", "cond(treatment)", "cond(climate:functional_group)", "cond(functional_group:treatment)", "cond(climate:functional_group)")
  
dredge_funct_sla <-  as.data.frame(dredge(funct_sla)) %>%
  filter(AICc == min(AICc)) %>%
  mutate(CWM = "Specific Leaf Area (log(x+1)") %>%
  dplyr::select(CWM, "cond(climate)", "cond(functional_group)", "cond(treatment)", "cond(climate:functional_group)")

dredge_funct_ldmc <- as.data.frame(dredge(funct_ldmc)) %>%
  filter(AICc == min(AICc)) %>%
  mutate(CWM = "Leaf Dry Matter Content (log)") %>%
dplyr::select(CWM, "cond(climate)", "cond(functional_group)", "cond(climate:functional_group)", "cond(functional_group:treatment)")

dredge_funct_seed_mass <- as.data.frame(dredge(funct_seed_mass)) %>%
  filter(AICc == min(AICc)) %>%
  mutate(CWM = "Seed Mass (log)") %>%
  dplyr::select(CWM, "cond(climate)", "cond(functional_group)", "cond(climate:functional_group)")

dredge_funct_n <- as.data.frame(dredge(funct_n)) %>%
  filter(AICc == min(AICc)) %>%
  mutate(CWM = "Leaf Nitrogen Content (log(x+1)") %>%
  dplyr::select(CWM, "cond(climate)", "cond(functional_group)", "cond(treatment)", "cond(climate:functional_group)")

dredge_table <- dredge_funct_la %>%
  full_join(dredge_funct_sla) %>%
  full_join(dredge_funct_ldmc) %>%
  full_join(dredge_funct_seed_mass) %>%
  full_join(dredge_funct_n) %>%
  mutate(Climate = str_replace(`cond(climate)`, "\\+","x")) %>%
  mutate(`Functional Group` = str_replace(`cond(functional_group)`, "\\+","x")) %>% 
  mutate(Treatment = str_replace(`cond(treatment)`, "\\+","x")) %>%
  mutate(`Climate:Functional Group` = str_replace(`cond(climate:functional_group)`, "\\+","x")) %>%
  mutate(`Climate:Treatment` = NA) %>%
  mutate(`Functional Group:Treatment` = str_replace(`cond(functional_group:treatment)`, "\\+","x")) %>%
  mutate(`Climate:Functional Group` = str_replace(`cond(climate:functional_group)`, "\\+","x")) %>% 
  dplyr::select(CWM, Climate, "Functional Group", Treatment, "Climate:Functional Group", "Climate:Treatment", "Functional Group:Treatment", "Climate:Functional Group")

dredge_table

knitr::kable(dredge_table)

# Trying gt package
# data must be a tibble

# pretty_table <- dredge_table %>%
#   as_tibble() %>%
#   gt() %>%
#   tab_header(
#     title = "Functional Group CWM Best-Fit Models"
#   ) %>%
#   tab_spanner(
#     label = "Fixed Effects Terms",
#     columns = vars(climate, functional_group, treatment, "climate:functional_group", "climate:treatment", "functional_group:treatment", "climate:functional_group")
#   ) %>%
#   fmt_missing(
#     columns = vars(climate, functional_group, treatment, "climate:functional_group", "climate:treatment", "functional_group:treatment", "climate:functional_group"),
#     missing_text = " "
#   ) %>%
#   tab_source_note(
#     source_note = "x indicates selection of fixed effect term for best-fit model"
#   )
# 
# pretty_table

# gtsave(data = pretty_table, filename = "Funct_Group_best_fit_table.png", path = "~/github/Tejon_Functional_Traits/Figures")
```

#### AIC Supplement
```{r, include=FALSE}
# dredge_funct_la <- as.data.frame(dredge(funct_la)) %>%
#   mutate(CWM = "Leaf Area (log(x+1))") %>%
#   dplyr::select(CWM, climate, functional_group, treatment, "climate:functional_group", "functional_group:treatment", "climate:functional_group", AICc)
# 
# dredge_funct_sla <-  as.data.frame(dredge(funct_sla)) %>%
#   mutate(CWM = "Specific Leaf Area (log(x+1)") %>%
#   dplyr::select(CWM, climate, functional_group, treatment, "climate:functional_group", AICc)
# 
# dredge_funct_ldmc <- as.data.frame(dredge(funct_ldmc)) %>%
#   mutate(CWM = "Leaf Dry Matter Content (log)") %>%
#   dplyr::select(CWM, climate, functional_group, treatment, "climate:functional_group", "functional_group:treatment", AICc)
# 
# dredge_funct_seed_mass <- as.data.frame(dredge(funct_seed_mass)) %>%
#   mutate(CWM = "Seed Mass (log)") %>%
#   dplyr::select(CWM, climate, functional_group, "climate:functional_group", AICc)
# 
# dredge_funct_n <- as.data.frame(dredge(funct_n)) %>%
#   mutate(CWM = "Leaf Nitrogen Content (log(x+1)") %>%
#   dplyr::select(CWM, climate, functional_group, treatment, "climate:functional_group", AICc)
# 
# dredge_table <- dredge_funct_la %>%
#   full_join(dredge_funct_sla) %>%
#   full_join(dredge_funct_ldmc) %>%
#   full_join(dredge_funct_seed_mass) %>%
#   full_join(dredge_funct_n) %>%
#   mutate(climate = str_replace(climate, "\\+","x")) %>%
#   mutate(functional_group = str_replace(functional_group, "\\+","x")) %>%
#   mutate(treatment = str_replace(treatment, "\\+","x")) %>%
#   mutate(`climate:functional_group` = str_replace(`climate:functional_group`, "\\+","x")) %>%
#   mutate(`climate:treatment` = NA) %>%
#   mutate(`functional_group:treatment` = str_replace(`functional_group:treatment`, "\\+","x")) %>%
#   mutate(`climate:functional_group` = str_replace(`climate:functional_group`, "\\+","x"))
# 
# # Trying gt package
# # data must be a tibble
# 
# funct_cwm_aic_sup <- dredge_table %>%
#   as_tibble() %>%
#   dplyr::group_by(CWM) %>%
#   gt() %>%
#   tab_header(
#     title = "Functional Group CWM Best-Fit Models"
#   ) %>%
#   tab_spanner(
#     label = "Fixed Effects Terms",
#     columns = vars(climate, functional_group, treatment, "climate:functional_group","climate:treatment", "functional_group:treatment", "climate:functional_group")
#   ) %>%
#   fmt_missing(
#     columns = vars(climate, functional_group, treatment, "climate:functional_group","climate:treatment", "functional_group:treatment", "climate:functional_group"),
#     missing_text = " "
#   ) %>%
#   tab_source_note(
#     source_note = "x indicates selection of fixed effect term for best-fit model"
#   ) %>%
#   cols_align(align = "center") %>%
#   tab_style(
#       style = cell_borders(
#         sides = c("left", "right"),
#         color = "#BBBBBB",
#         weight = px(1.5),
#         style = "solid"
#       ),
#       locations = cells_body(
#         columns = everything(),
#         rows = everything()
#       )
#     )
# 
# # funct_cwm_aic_sup
# 
# # gtsave(data = funct_cwm_aic_sup, filename = "Funct_Group_AIC_Supp.png", path = "~/github/Tejon_Functional_Traits/Figures")
```

