---
title: "funct_group_individual"
author: "Maggie Klope"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(stats)
library(sjPlot)
library(FD)
library(DHARMa) #model diagnostics
library(glmmTMB) #model fitting
library(MuMIn) #model summaries and comparisons
library(emmeans) #post-hoc analyses
library(gt)
library(tibble)
library(lsmeans)
library(gridExtra)
library(multcomp)
library(car)
library(ggeffects)

other_traits <- read_csv("Datasheets/seed_mass_leaf_N.csv")

cwm_traits_adj <-  read_csv("Datasheets/cwm_traits_updated.csv") %>% 
  left_join(other_traits, by = "species_name") %>% 
  mutate(weighted_la = leaf_area * Abundance) %>% #multiplying trait values by species abundance
  mutate(weighted_sla = sla * Abundance) %>% 
  mutate(weighted_ldmc = ldmc * Abundance) %>%
  mutate(weighted_seed_mass = seed_mass * Abundance) %>%
  mutate(weighted_n = leaf_n * Abundance) %>%
  group_by(climate, treatment, Block) %>% #grouping by climate, treatment, and block
  summarise_all(mean, na.rm = TRUE) %>% #finding the mean
  dplyr::select(climate, treatment, Block, weighted_la, weighted_sla, weighted_ldmc, weighted_seed_mass, weighted_n)

# log transformation for seed mass & leaf n
cwm_traits_adj <- cwm_traits_adj %>% 
  mutate(log_seed_mass = log(weighted_seed_mass)) %>% 
  mutate(log_n = log(weighted_n))

```

#### a. grasses:
##### i. leaf area
```{r}
grass_la <- glm(data = grass, weighted_la ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_la) # best model: trait ~ climate * treatment

simulateResiduals(grass_la, plot= T) #good
shapiro.test(residuals(grass_la)) #normal

summary(grass_la)
emmeans(grass_la, pairwise ~ climate)
emmeans(grass_la, pairwise ~ treatment | climate)
```
##### ii. specific leaf area
```{r}
grass_sla <- glm(data = grass, weighted_sla ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_sla) # best model: trait ~ climate * treatment

simulateResiduals(grass_sla, plot= T) # good
shapiro.test(residuals(grass_sla)) # normal

summary(grass_sla)
emmeans(grass_sla, pairwise ~ climate)
emmeans(grass_sla, pairwise ~ treatment | climate)
```
##### iii.ldmc
```{r}
grass_ldmc <- glm(data = grass, weighted_ldmc ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_ldmc) # best model: trait ~ climate + treatment
grass_ldmc <- glm(data = grass, weighted_ldmc ~ climate + treatment, family = gaussian, na.action = na.fail)

simulateResiduals(grass_ldmc, plot= T) # not good
shapiro.test(residuals(grass_ldmc)) # not normal

grass <- grass %>% 
  mutate(log_ldmc = log(weighted_ldmc))

grass_ldmc <- glm(data = grass, log_ldmc ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_ldmc) # best model: trait ~ climate
grass_ldmc <- glm(data = grass, log_ldmc ~ climate, family = gaussian, na.action = na.fail)

simulateResiduals(grass_ldmc, plot= T) # good
shapiro.test(residuals(grass_ldmc)) # normal

summary(grass_ldmc)
emmeans(grass_ldmc, pairwise ~ climate)
```
##### iv. lnc
```{r}
grass_n <- glm(data = grass, weighted_n ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_n) # best model: trait ~ climate
grass_n <- glm(data = grass, weighted_n ~ climate, family = gaussian, na.action = na.fail)

simulateResiduals(grass_n, plot= T) # good
shapiro.test(residuals(grass_n)) # normal

summary(grass_n)
emmeans(grass_n, pairwise ~ climate)
```
##### v. seed mass
```{r}
grass_seed_mass <- glm(data = grass, weighted_seed_mass ~ climate * treatment, family = gaussian, na.action = na.fail)
boxcox(grass_seed_mass) # might be best to do ln transformation
dredge(grass_seed_mass) # best model: trait ~ climate + treatment
grass_seed_mass <- glm(data = grass, weighted_seed_mass ~ climate + treatment, family = gaussian, na.action = na.fail)

simulateResiduals(grass_seed_mass, plot= T) # not good
shapiro.test(residuals(grass_seed_mass)) # normal

grass <- grass %>% 
  mutate(log_seed_mass = log(weighted_seed_mass)) %>% 
  mutate(ln_seed_mass = log10(weighted_seed_mass)) %>% 
  mutate(sqrt_seed_mass = sqrt(weighted_seed_mass))

grass_seed_mass <- glm(data = grass, log_seed_mass ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_seed_mass) # best model: trait ~ climate
grass_seed_mass <- glm(data = grass, log_seed_mass ~ climate, family = gaussian, na.action = na.fail)

simulateResiduals(grass_seed_mass, plot= T) # ok?
shapiro.test(residuals(grass_seed_mass)) # not normal

grass_seed_mass <- glm(data = grass, ln_seed_mass ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_seed_mass) # best model: trait ~ climate
grass_seed_mass <- glm(data = grass, ln_seed_mass ~ climate, family = gaussian, na.action = na.fail)

simulateResiduals(grass_seed_mass, plot= T) # ok?
shapiro.test(residuals(grass_seed_mass)) # not normal

grass_seed_mass <- glm(data = grass, sqrt_seed_mass ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(grass_seed_mass) # best model: trait ~ climate + treatment
grass_seed_mass <- glm(data = grass, sqrt_seed_mass ~ climate + treatment, family = gaussian, na.action = na.fail)

simulateResiduals(grass_seed_mass, plot= T) # not ok
shapiro.test(residuals(grass_seed_mass)) # normal

# gamma distribution worked all along
grass_seed_mass <- glm(data = grass, weighted_seed_mass ~ climate * treatment, family = Gamma, na.action = na.fail)
dredge(grass_seed_mass) # best model: trait ~ climate + treatment
grass_seed_mass <- glm(data = grass, weighted_seed_mass ~ climate + treatment, family = Gamma, na.action = na.fail)

simulateResiduals(grass_seed_mass, plot= T) # good
shapiro.test(residuals(grass_seed_mass)) # normal

summary(grass_seed_mass)
emmeans(grass_seed_mass, pairwise ~ climate)
emmeans(grass_seed_mass, pairwise ~ treatment | climate)
```
#### b. forbs
##### i. la
```{r}
forb_la <- glm(data = forb, log_la ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(forb_la) # best model is climate + treatment
forb_la <- glm(data = forb, log_la ~ climate + treatment, family = gaussian, na.action = na.fail)

simulateResiduals(forb_la, plot= T) # ok
shapiro.test(residuals(forb_la)) #normal

summary(forb_la)
emmeans(forb_la, pairwise ~ climate)
emmeans(forb_la, pairwise ~ treatment | climate)
```
##### ii. sla
```{r}
forb_sla <- glm(data = forb, weighted_sla ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(forb_sla) # best model is only climate
forb_sla <- glm(data = forb, weighted_sla ~ climate, family = gaussian, na.action = na.fail)

simulateResiduals(forb_sla, plot= T) # ok
shapiro.test(residuals(forb_sla)) # not normal

forb_sla <- glm(data = forb, weighted_sla ~ climate * treatment, family = Gamma, na.action = na.fail)
dredge(forb_sla) # best model: trait ~ climate
forb_sla <- glm(data = forb, weighted_sla ~ climate, family = Gamma, na.action = na.fail)

simulateResiduals(forb_sla, plot= T) # ok
shapiro.test(residuals(forb_sla)) # normal

summary(forb_sla)
emmeans(forb_sla, pairwise ~ climate)
```
##### iii. ldmc
```{r}
forb_ldmc <- glm(data = forb, weighted_ldmc ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(forb_ldmc) # best model: trait ~ treatment
forb_ldmc <- glm(data = forb, weighted_ldmc ~ treatment, family = gaussian, na.action = na.fail)

simulateResiduals(forb_ldmc, plot= T) # ok
shapiro.test(residuals(forb_ldmc)) # normal

summary(forb_ldmc)
emmeans(forb_ldmc, pairwise ~ treatment)
```
##### iv.lnc
```{r}
forb_leaf_n <- glm(data = forb, weighted_n ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(forb_leaf_n) # best model: trait ~ climate
forb_leaf_n <- glm(data = forb, weighted_n ~ climate, family = gaussian, na.action = na.fail)

simulateResiduals(forb_leaf_n, plot= T) # ok
shapiro.test(residuals(forb_leaf_n)) # normal

summary(forb_leaf_n)
emmeans(forb_leaf_n, pairwise ~ climate)
```
##### v.seed mass
```{r}
forb_seed_mass <- glm(data = forb, weighted_seed_mass ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(forb_seed_mass) # best model: trait ~ climate * treatment

simulateResiduals(forb_seed_mass, plot= T) # not good
shapiro.test(residuals(forb_seed_mass)) # not normal

forb_seed_mass <- glm(data = forb, weighted_seed_mass ~ climate * treatment, family = Gamma, na.action = na.fail)
dredge(forb_seed_mass) # best model: trait ~ climate * treatment

simulateResiduals(forb_seed_mass, plot= T) # ok
shapiro.test(residuals(forb_seed_mass)) # not normal

forb <- forb %>% 
  mutate(log_seed_mass = log(weighted_seed_mass))

forb_seed_mass <- glm(data = forb, log_seed_mass ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(forb_seed_mass) # best model: trait ~ climate
forb_seed_mass <- glm(data = forb, log_seed_mass ~ climate, family = gaussian, na.action = na.fail)

simulateResiduals(forb_seed_mass, plot= T) # ok
shapiro.test(residuals(forb_seed_mass)) # normal

summary(forb_seed_mass)
emmeans(forb_seed_mass, pairwise ~ climate)
```
#### c. shrubs
##### i.la
- what do you do when residuals are normal but the residual vs. predicted plot looks terrible?
```{r}
shrub_la <- glm(data = shrub, weighted_la ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(shrub_la) # best model: trait ~ climate + treatment
shrub_la  <- glm(data = shrub, weighted_la ~ climate + treatment, family = gaussian, na.action = na.fail)

simulateResiduals(shrub_la, plot= T) # very bad
shapiro.test(residuals(shrub_la)) # normal

summary(shrub_la)
emmeans(shrub_la, pairwise ~ climate)
```
##### ii.sla
```{r}
shrub_sla <- glm(data = shrub, weighted_sla ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(shrub_sla) # best model: trait ~ 1
shrub_sla  <- glm(data = shrub, weighted_sla ~ 1, family = gaussian, na.action = na.fail)

simulateResiduals(shrub_sla, plot= T) # fine
shapiro.test(residuals(shrub_sla)) # normal

```
##### iii.ldmc
```{r}
shrub_ldmc <- glm(data = shrub, weighted_ldmc ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(shrub_ldmc) # best model: trait ~ treatment; NEED TO DO MODEL AVERAGING
shrub_ldmc  <- glm(data = shrub, weighted_ldmc ~ treatment, family = gaussian, na.action = na.fail)

simulateResiduals(shrub_ldmc, plot= T) # fine
shapiro.test(residuals(shrub_ldmc)) # normal

summary(shrub_ldmc)
emmeans(shrub_ldmc, pairwise ~ treatment)
```
##### iv.lnc
```{r}
shrub_n <- glm(data = shrub, weighted_n ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(shrub_n) # NEED TO DO MODEL AVERAGING
shrub_n  <- glm(data = shrub, weighted_n ~ treatment, family = gaussian, na.action = na.fail)

simulateResiduals(shrub_n, plot= T) # fine
shapiro.test(residuals(shrub_n)) # normal

summary(shrub_n)
emmeans(shrub_n, pairwise ~ treatment)
```
##### v.seed mass
```{r}
shrub_seed_mass <- glm(data = shrub, weighted_seed_mass ~ climate * treatment, family = gaussian, na.action = na.fail)
dredge(shrub_seed_mass) # NEED TO DO MODEL AVERAGING
shrub_seed_mass  <- glm(data = shrub, weighted_seed_mass ~ climate + treatment, family = gaussian, na.action = na.fail)

simulateResiduals(shrub_seed_mass, plot= T) # bad
shapiro.test(residuals(shrub_seed_mass)) # normal

summary(shrub_n)
emmeans(shrub_n, pairwise ~ treatment)

```

