---
title: "funct_group_graphs"
author: "Maggie Klope"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. EMM Graphs
```{r}
# color of arrows
arrow_colors <- (rep(c("red", "orange", "blue"), 9))

funct_emm_plot <- function(emmeans) {
  plot(emmeans, type = "response", by = NULL, CIs = FALSE, comparisons = TRUE, horizontal = FALSE, colors = "black") +
    # geom_segment(aes_(y = ~the.emmean, yend = ~lcmpl, x = ~pri.fac, xend = ~pri.fac), 
    #            arrow = arrow(length = ggplot2::unit(.07, "inches"), type = "closed"),
    #            color ="black") +
    # geom_segment(ggplot2::aes_(y = ~the.emmean, yend = ~rcmpl, x = ~pri.fac, xend = ~pri.fac),
    #            arrow = arrow(length = ggplot2::unit(.07, "inches"), type = "closed"),
    #            color = "black") +
    # geom_point(aes_(fill = "black")) +
    theme(legend.position = "none")
}

# The geom_segment() code to change the color of the arrows (by just adding in different arrows over the top) does not work this way because some of the arrows do not overlap the points

```
#### a. Seed Mass
```{r}
# method 1 for plotting back transformation: 
# re-writing with the transformation in the model
funct_seed_mass <- glm(data = cwm_functional, log(weighted_seed_mass) ~ climate + functional_group + climate:functional_group, na.action = na.fail)

# use emmeans()
funct_seed_mass_emm <- emmeans(funct_seed_mass, ~ climate * functional_group)

# then plot with type = "response"

seed_mass_plot_1 <- funct_emm_plot(funct_seed_mass_emm)+
  facet_grid(. ~ functional_group, scales = "free", space = "free") +
  scale_x_discrete(labels = rep(c("Arid", "Intermediate", "Mesic"), 9)) +
  labs(title = "Seed Mass CWM by Functional Group", y = "Seed Mass (mg)", x = "Climate")

# method 2 for plotting back transformation:
# this uses the model that used the already transformed data
funct_seed_mass <- glm(data = cwm_functional, log_seed_mass ~ climate + functional_group + climate:functional_group, na.action = na.fail)

# updating with transformation information
funct_seed_mass.rg <- update(ref_grid(funct_seed_mass), tran = "log")

# plot
seed_mass_plot_2 <- funct_emm_plot(funct_seed_mass.rg)+
  facet_grid(. ~ functional_group, scales = "free", space = "free") +
  scale_x_discrete(labels = rep(c("Arid", "Intermediate", "Mesic"), 9)) +
  labs(title = "Seed Mass CWM by Functional Group", y = "Seed Mass (mg)", x = "Climate")

seed_mass_plot_1
seed_mass_plot_2

# ggsave("funct_seed_mass_plot.png", path = "~/github/Tejon_Functional_Traits/Figures", width = 10, height = 7, bg = "transparent")
```
#### b. Specific Leaf Area
```{r}
# log(x+1) transformation
# funct_sla <- glm(data = cwm_functional, log_plus_sla ~ climate + functional_group + treatment + climate:functional_group, family = gaussian, na.action = na.fail)

funct_sla <- glm(data = cwm_functional, log(weighted_sla + 1) ~ climate + functional_group + treatment + climate:functional_group, family = gaussian, na.action = na.fail)

funct_sla_emm <- emmeans(funct_sla, ~ climate + functional_group + treatment + climate:functional_group)

emmeans(funct_sla, pairwise ~ climate + functional_group + treatment + climate:functional_group)

# plot

funct_emm_plot(funct_sla_emm) +
  facet_grid(. ~ functional_group + climate, scales = "free", space = "free") +
  aes(fill = as.factor(treatment)) +
  scale_x_discrete(labels = rep(c("Open", "Partial", "Total"), 9)) +
  labs(title = "Specific Leaf Area CWM by Functional Group", x = "Treatment") +
  theme(panel.margin = unit(0, "lines"),
        panel.border = element_rect(color = "black", fill = NA, size = 0.5),
        panel.background = element_rect(fill = c("#E2F0D9", "#DEEBF7")))


plot(funct_sla_emm, type = "response", by = NULL, CIs = FALSE, comparisons = TRUE, horizontal = FALSE, colors = "black") +
    facet_grid(. ~ functional_group + climate, scales = "free", space = "free") +
    aes(fill = as.factor(treatment)) +
    scale_x_discrete(labels = rep(c("Open", "Partial", "Total"), 9)) +
    labs(title = "Specific Leaf Area CWM by Functional Group", x = "Treatment") +
    # theme(panel.margin = unit(0, "lines"),
    #     panel.border = element_rect(color = "black", fill = NA, size = 0.5),
    #     strip.background.x = element_rect(fill = c("#E2F0D9", "#DEEBF7")),
    #     strip.text.x = element_blank()
    #     ) + 
    theme(legend.position = "none")
  
plot(funct_sla_emm, by = NULL, CIs = FALSE, comparisons = TRUE, horizontal = FALSE, colors = "black") +
  facet_grid(. ~ functional_group + climate, scales = "free", space = "free", 
             labeller = label_wrap_gen(multi_line=FALSE))

plot(funct_sla_emm, by = NULL, CIs = FALSE, comparisons = TRUE, horizontal = FALSE, colors = "black") +
  facet_grid(. ~ functional_group + climate, scales = "free", space = "free", 
             labeller = label_wrap_gen(multi_line=FALSE),
             labeller = as_labeller(c(
               'forb, Arid' = "Forb", 'forb, Intermediate' = "Forb", 'Forb, Meisc' = "Forb", 
               'grass, Arid' = "grass", 'grass, Intermediate' = "grass", 'grass, Meisc' = "shrub", 
               'shrub, Arid' = "shrub", 'shrub, Intermediate' = "shrub", 'shrub, Meisc' = "shrub")))

emmeans(funct_sla, pairwise ~ treatment)


```
#### c. Leaf Area
```{r}
funct_la_emm <- emmeans(funct_la, pairwise ~ treatment + climate + functional_group)

# emmeans(funct_la, pairwise ~ treatment | climate | functional_group)

funct_la_plot <- plot(la_emmeans, by = NULL, CIs = FALSE, comparisons = TRUE, horizontal = FALSE, colors = "darkgreen") +
  facet_grid(. ~ functional_group + climate, scales = "free", space = "free") +
  aes(fill = as.factor(treatment)) +
   geom_segment(aes_(y = ~the.emmean, yend = ~lcmpl, x = ~pri.fac, xend = ~pri.fac), #copied from function's code on github
               arrow = arrow(length = ggplot2::unit(.07, "inches"), type = "closed"),
               color ="black") +
  geom_segment(ggplot2::aes_(y = ~the.emmean, yend = ~rcmpl, x = ~pri.fac, xend = ~pri.fac),
               arrow = arrow(length = ggplot2::unit(.07, "inches"), type = "closed"),
               color = "black") +
  geom_point(aes_(fill = "black")) +
  # theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
  scale_x_discrete(labels = rep(c("Open", "Partial", "Total"), 9)) +
  labs(title = "Leaf Area CWM by Functional Group") +
    theme(legend.position = "none")

funct_la_plot 

# ggsave("funct_la_plot.png", path = "~/github/Tejon_Functional_Traits/Figures", width = 10, height = 7, bg = "transparent")


```

## 2. ggeffects Graphs
#### a. fist try
```{r}
ggeffects_colors <- c("#f46d43", "#fee090", "#74add1")

# First try
funct_la_plot <- plot(ggpredict(funct_la, terms = c("treatment", "climate", "functional_group")), colors = ggeffects_colors, facet = TRUE)
funct_sla_plot <- plot(ggpredict(funct_sla, terms = c("treatment", "climate", "functional_group")), colors = ggeffects_colors,facet = TRUE)
funct_ldmc_plot <- plot(ggpredict(funct_ldmc, terms = c("treatment", "climate", "functional_group")), colors = ggeffects_colors,facet = TRUE)
funct_n_plot <- plot(ggpredict(funct_n, terms = c("treatment", "climate", "functional_group")), colors = ggeffects_colors,facet = TRUE)
funct_seed_mass_plot <- plot(ggpredict(funct_seed_mass, terms = c("climate", "functional_group")), colors = ggeffects_colors,facet = TRUE)
funct_group_CWM_emmeans <- grid.arrange(funct_la_plot, funct_sla_plot, funct_ldmc_plot, funct_n_plot, funct_seed_mass_plot)

# ggsave("funct_group_CWM_emmeans.png", plot = funct_group_CWM_emmeans, path = "~/github/Tejon_Functional_Traits/Figures/ggeffects_graphs", height = 7, width = 10)

```
### b. adding significance

##### i. creating a function
```{r}
funct_graph <- function(model, model_terms, title, y_lab, x_lab){
  
  predict <- ggpredict(model, terms = model_terms)
  test <- as.data.frame(predict)
  
  ggplot(test, aes(facet, predicted, color = x)) +
  geom_point(position = position_dodge(width=0.5)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), 
                width = .25, 
                size = .75,
                position = position_dodge(width=0.5))+
  scale_color_manual(values = ggeffects_colors) +
  theme(
    panel.background = element_rect(fill = "white",
                                    colour = "white",
                                    size = 0.5, linetype = "solid"),
    panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                    colour = "gray90"),
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                    colour = "gray90"),
    axis.line = element_line(size = 0.5, linetype = "solid",
                             colour = "gray85"),
    strip.background = element_rect(fill = "gray85"),
    strip.text = element_text(colour = 'gray20')
  ) +
  labs(title = title, y = y_lab, x = x_lab) +
  facet_grid(~ group)
}
```

##### ii. Leaf Area
```{r}
# making annotation file
anno <- as.data.frame(summary(emmeans(funct_la, specs = pairwise ~ climate + treatment + functional_group))$contrasts) %>%
  filter(p.value <= 0.05) %>% 
  separate(col = contrast, into = c("plot_1", "plot_2"), sep = " - ") %>% 
  separate(col = plot_1, into = c("plot_1_climate", "plot_1_treatment", "plot_1_funct_group"), sep = ",") %>% 
  separate(col = plot_2, into = c("plot_2_climate", "plot_2_treatment", "plot_2_funct_group"), sep = ",") %>% 
  filter(plot_1_funct_group == plot_2_funct_group & plot_1_climate == plot_2_climate) %>% 
  rename(group = plot_2_funct_group, start = plot_1_treatment, end = plot_2_treatment, climate = plot_1_climate) %>%
  mutate(label = ifelse(p.value > .05, "*",
                        ifelse(p.value <= 0.01, "**",
                               ifelse(p.value <= 0.001, "***", "****")))) %>% 
  dplyr::select(group, start, end, label, climate)

# splitting up by climate
arid_anno <- anno %>% 
  filter(climate == "Arid")
int_anno <- anno %>% 
  filter(climate == "Intermediate")
mesic_anno <- anno %>% 
  filter(climate == "Mesic")

# graphing
funct_graph(model = funct_la, 
            model_terms = c("climate", "functional_group", "treatment"),
            title = "Leaf Area CWM by Functional Group",
            y_lab = "Predicted log(CWM Leaf Area + 1)",
            x_lab = "Herbivore Treatment") +
  geom_signif(
        data = arid_anno,
        aes(xmin = start, xmax = end, annotations = label, y_position = 4.25),
        color = "#f46d43",
      manual = TRUE) +
  geom_signif(
    data = int_anno,
    aes(xmin = start, xmax = end, annotations = label, y_position = 4.5),
    color = "#fee090",
    manual = TRUE) +
  geom_signif(
    data = mesic_anno,
    aes(xmin = start, xmax = end, annotations = label, y_position = 4.75),
    color = "#74add1",
    manual = TRUE)

```

##### iii. Specific Leaf Area
```{r}
# no significant differences to annotate

# anno <- as.data.frame(summary(emmeans(funct_sla, specs = pairwise ~ climate + treatment + functional_group))$contrasts) %>%
#   filter(p.value <= 0.05) %>% 
#   separate(col = contrast, into = c("plot_1", "plot_2"), sep = " - ") %>% 
#   separate(col = plot_1, into = c("plot_1_climate", "plot_1_treatment", "plot_1_funct_group"), sep = ",") %>% 
#   separate(col = plot_2, into = c("plot_2_climate", "plot_2_treatment", "plot_2_funct_group"), sep = ",") %>% 
#   filter(plot_1_funct_group == plot_2_funct_group & plot_1_climate == plot_2_climate) %>% 
#   rename(group = plot_2_funct_group, start = plot_1_treatment, end = plot_2_treatment, climate = plot_1_climate) %>%
#   mutate(label = ifelse(p.value > .05, "*",
#                         ifelse(p.value <= 0.01, "**",
#                                ifelse(p.value <= 0.001, "***", "****")))) %>% 
#   dplyr::select(group, start, end, label, climate)

funct_graph(model = funct_sla, 
            model_terms = c("climate", "functional_group", "treatment"),
            title = "Specific Leaf Area CWM by Functional Group",
            y_lab = "Predicted log(CWM Specific Leaf Area + 1)",
            x_lab = "Herbivore Treatment")

```

##### iv. Leaf Dry Matter Content
```{r}
# creating annotations
anno <- as.data.frame(summary(emmeans(funct_ldmc, specs = pairwise ~ climate + treatment + functional_group))$contrasts) %>%
  filter(p.value <= 0.05) %>%
  separate(col = contrast, into = c("plot_1", "plot_2"), sep = " - ") %>%
  separate(col = plot_1, into = c("plot_1_climate", "plot_1_treatment", "plot_1_funct_group"), sep = ",") %>%
  separate(col = plot_2, into = c("plot_2_climate", "plot_2_treatment", "plot_2_funct_group"), sep = ",") %>%
  filter(plot_1_funct_group == plot_2_funct_group & plot_1_climate == plot_2_climate) %>%
  rename(group = plot_2_funct_group, start = plot_1_treatment, end = plot_2_treatment, climate = plot_1_climate) %>%
  mutate(label = ifelse(p.value > .05, "*",
                        ifelse(p.value <= 0.01, "**",
                               ifelse(p.value <= 0.001, "***", "****")))) %>%
  dplyr::select(group, start, end, label, climate)

# splitting anootation by climate
arid_anno <- anno %>% 
  filter(climate == "Arid")
int_anno <- anno %>% 
  filter(climate == "Intermediate")
mesic_anno <- anno %>% 
  filter(climate == "Mesic")

# graphing
funct_graph(model = funct_ldmc, 
            model_terms = c("climate", "functional_group", "treatment"),
            title = "Leaf Dry Matter Content CWM by Functional Group",
            y_lab = "Predicted log(CWM Leaf Dry Matter Content)",
            x_lab = "Herbivore Treatment") +
  geom_signif(
        data = arid_anno,
        aes(xmin = start, xmax = end, annotations = label, y_position = 4.25),
        color = "#f46d43",
      manual = TRUE) +
  geom_signif(
    data = int_anno,
    aes(xmin = start, xmax = end, annotations = label, y_position = 4.5),
    color = "#fee090",
    manual = TRUE) +
  geom_signif(
    data = mesic_anno,
    aes(xmin = start, xmax = end, annotations = label, y_position = 4.75),
    color = "#74add1",
    manual = TRUE)
```

##### vi. Seed Mass
```{r}
# model does not contain treatment

anno <- as.data.frame(summary(emmeans(funct_seed_mass, specs = pairwise ~ climate + functional_group))$contrasts) %>%
  filter(p.value <= 0.05) %>%
  separate(col = contrast, into = c("plot_1", "plot_2"), sep = " - ") %>%
  separate(col = plot_1, into = c("plot_1_climate", "plot_1_funct_group"), sep = ",") %>%
  separate(col = plot_2, into = c("plot_2_climate", "plot_2_funct_group"), sep = ",") %>%
  filter(plot_1_funct_group == plot_2_funct_group) %>%
  rename(group = plot_2_funct_group, start = plot_1_climate, end = plot_2_climate) %>%
  mutate(label = ifelse(p.value > .05, "*",
                        ifelse(p.value <= 0.01, "**",
                               ifelse(p.value <= 0.001, "***", "****")))) %>%
  dplyr::select(group, start, end, label)
anno

predict <- ggpredict(funct_seed_mass, terms = c("climate", "functional_group"))
test <- as.data.frame(predict)
test

ggplot(test, aes(x, predicted)) +
  geom_point(position = position_dodge(width=0.5),
             aes(color = x)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high, color = x), 
                width = .25, 
                size = .75,
                position = position_dodge(width=0.5))+
  scale_color_manual(values = ggeffects_colors) +
  theme(
    panel.background = element_rect(fill = "white",
                                    colour = "white",
                                    size = 0.5, linetype = "solid"),
    panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                    colour = "gray90"),
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                    colour = "gray90"),
    axis.line = element_line(size = 0.5, linetype = "solid",
                             colour = "gray85"),
    strip.background = element_rect(fill = "gray85"),
    strip.text = element_text(colour = 'gray20')
  ) +
  labs(title = "Functional Group Seed Mass CWM", y = "Predicted log(Seed Mass CWM)", x = "Climate") +
  geom_signif(
    data = anno,
    aes(xmin = start, xmax = end, annotations = label, y_position = c(-1, -.5, .5, 1, .5, 1)),
    manual = TRUE) +
  facet_grid(~ group)


```

##### vii. LNC
```{r}
# no significant differences to annotate

# # creating annotations
# anno <- as.data.frame(summary(emmeans(funct_n, specs = pairwise ~ climate + treatment + functional_group))$contrasts) %>%
#   filter(p.value <= 0.05) %>%
#   separate(col = contrast, into = c("plot_1", "plot_2"), sep = " - ") %>%
#   separate(col = plot_1, into = c("plot_1_climate", "plot_1_treatment", "plot_1_funct_group"), sep = ",") %>%
#   separate(col = plot_2, into = c("plot_2_climate", "plot_2_treatment", "plot_2_funct_group"), sep = ",") %>%
#   filter(plot_1_funct_group == plot_2_funct_group & plot_1_climate == plot_2_climate) %>%
#   rename(group = plot_2_funct_group, start = plot_1_treatment, end = plot_2_treatment, climate = plot_1_climate) %>%
#   mutate(label = ifelse(p.value > .05, "*",
#                         ifelse(p.value <= 0.01, "**",
#                                ifelse(p.value <= 0.001, "***", "****")))) %>%
#   dplyr::select(group, start, end, label, climate)

funct_graph(model = funct_n, 
            model_terms = c("climate", "functional_group", "treatment"),
            title = "Leaf Nitrogen Concentration CWM by Functional Group",
            y_lab = "Predicted log(Leaf Nitrogen Concentration CWM + 1)",
            x_lab = "Herbivore Treatment")


```

## 3. sjPlot [NOT USING]
```{r}
# library(sjPlot)
# 
# plot_model(funct_la, type = "emm", terms = c("climate", "treatment", "functional_group"))
# 
# plot_model(funct_sla, type = "emm", terms = c("climate", "treatment", "functional_group"))
```
