---
title: "Functional_Diversity"
author: "Maggie Klope"
date: "10/18/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(stats)
library(sjPlot)
library(FD)
library(DHARMa) #model diagnostics
library(glmmTMB) #model fitting
library(MuMIn) #model summaries and comparisons
library(emmeans) #post-hoc analyses
# library(performance) #for R2 values
library(gt)
library(knitr)
library(ggsignif) # for adding significance comparisons to graphs
library(ggeffects)
library(gridExtra)
library(car)
```

```{r tidy data, include=FALSE}
other_traits <- read_csv("/Users/User_2/github/Tejon_Functional_Traits/Datasheets/seed_mass_leaf_N.csv")

#making a df just for functional diveristy calculations
for_FD <- read_csv("/Users/User_2/github/Tejon_Functional_Traits/Datasheets/cwm_traits_updated.csv") %>% 
  left_join(other_traits, by = "species_name") %>% 
  dplyr::select(climate, treatment, Block, species_name, Abundance, leaf_area, sla, ldmc, seed_mass, leaf_n) %>%
  drop_na

#abundance data in correct format:
fd_abund <- function(Climate, Treatment){
  as.matrix(for_FD %>% 
    filter(climate == Climate) %>% 
    filter(treatment == Treatment) %>% 
    arrange(species_name) %>% 
    dplyr::select(Block, species_name, Abundance) %>%
    pivot_wider(names_from = species_name, values_from = Abundance) %>%
    replace(is.na(.), 0) %>% 
    column_to_rownames(var = "Block"))
}

arid_open_abund <- fd_abund("Arid", "Open")
arid_partial_abund <- fd_abund("Arid", "Partial")
arid_total_abund  <- fd_abund("Arid", "Total")

int_open_abund <- fd_abund("Intermediate", "Open")
int_partial_abund <- fd_abund("Intermediate", "Partial")
int_total_abund <- fd_abund("Intermediate", "Total")

mesic_open_abund <- fd_abund("Mesic", "Open")
mesic_partial_abund <- fd_abund("Mesic", "Partial")
mesic_total_abund <- fd_abund("Mesic", "Total")

# trait data in correct format:

fd_traits <- function(Climate, Treatment){
  for_FD %>% 
    # ungroup(climate, treatment) %>% 
    filter(climate == Climate) %>% 
    filter(treatment == Treatment) %>% 
    dplyr::select(species_name, leaf_area, sla, ldmc) %>%
    distinct() %>% 
    arrange(species_name) %>% 
    column_to_rownames(var = "species_name") 
  
}

arid_open_trait <- fd_traits("Arid", "Open")
arid_partial_trait <- fd_traits("Arid", "Partial")
arid_total_trait <- fd_traits("Arid", "Total")

int_open_trait <- fd_traits("Intermediate", "Open")
int_partial_trait <- fd_traits("Intermediate", "Partial")
int_total_trait <- fd_traits("Intermediate", "Total")

mesic_open_trait <- fd_traits("Mesic", "Open")
mesic_partial_trait <- fd_traits("Mesic", "Partial")
mesic_total_trait <- fd_traits("Mesic", "Total")
```

```{r FD calcs, include=FALSE}
arid_open_fd <- dbFD(x = arid_open_trait, a = arid_open_abund)
arid_partial_fd <- dbFD(x = arid_partial_trait, a = arid_partial_abund)
arid_total_fd <- dbFD(x = arid_total_trait, a = arid_total_abund)

int_open_fd <- dbFD(x = int_open_trait, a = int_open_abund)
int_partial_fd <- dbFD(x = int_partial_trait, a = int_partial_abund)
int_total_fd <- dbFD(x = int_total_trait, a = int_total_abund)

mesic_open_fd <- dbFD(x = mesic_open_trait, a = mesic_open_abund)
mesic_partial_fd <- dbFD(x = mesic_partial_trait, a = mesic_partial_abund)
mesic_total_fd <- dbFD(x = mesic_total_trait, a = mesic_total_abund)

FD_arid_open <- as.data.frame(arid_open_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "arid_open_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Arid") %>% 
  mutate(treatment = "Open") %>% 
  mutate(FEve = arid_open_fd$FEve) %>% 
  mutate(FDiv = arid_open_fd$FDiv) %>% 
  mutate(FDis = arid_open_fd$FDis) %>% 
  mutate(RaoQ = arid_open_fd$RaoQ)
  
FD_arid_partial <- as.data.frame(arid_partial_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "arid_partial_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Arid") %>% 
  mutate(treatment = "Partial")%>% 
  mutate(FEve = arid_partial_fd$FEve) %>% 
  mutate(FDiv = arid_partial_fd$FDiv) %>% 
  mutate(FDis = arid_partial_fd$FDis) %>% 
  mutate(RaoQ = arid_partial_fd$RaoQ)

FD_arid_total <- as.data.frame(arid_total_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "arid_total_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Arid") %>% 
  mutate(treatment = "Total")%>% 
  mutate(FEve = arid_total_fd$FEve) %>% 
  mutate(FDiv = arid_total_fd$FDiv) %>% 
  mutate(FDis = arid_total_fd$FDis) %>% 
  mutate(RaoQ = arid_total_fd$RaoQ)

FD_int_open <- as.data.frame(int_open_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "int_open_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Intermediate") %>% 
  mutate(treatment = "Open")%>% 
  mutate(FEve = int_open_fd$FEve) %>% 
  mutate(FDiv = int_open_fd$FDiv) %>% 
  mutate(FDis = int_open_fd$FDis) %>% 
  mutate(RaoQ = int_open_fd$RaoQ)

FD_int_partial <- as.data.frame(int_partial_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "int_partial_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Intermediate") %>% 
  mutate(treatment = "Partial")%>% 
  mutate(FEve = int_partial_fd$FEve) %>% 
  mutate(FDiv = int_partial_fd$FDiv) %>% 
  mutate(FDis = int_partial_fd$FDis) %>% 
  mutate(RaoQ = int_partial_fd$RaoQ)

FD_int_total <- as.data.frame(int_total_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "int_total_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Intermediate") %>% 
  mutate(treatment = "Total")%>% 
  mutate(FEve = int_total_fd$FEve) %>% 
  mutate(FDiv = int_total_fd$FDiv) %>% 
  mutate(FDis = int_total_fd$FDis) %>% 
  mutate(RaoQ = int_total_fd$RaoQ)

FD_mesic_open <- as.data.frame(mesic_open_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "mesic_open_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Mesic") %>% 
  mutate(treatment = "Open")%>% 
  mutate(FEve = mesic_open_fd$FEve) %>% 
  mutate(FDiv = mesic_open_fd$FDiv) %>% 
  mutate(FDis = mesic_open_fd$FDis) %>% 
  mutate(RaoQ = mesic_open_fd$RaoQ)

FD_mesic_partial <- as.data.frame(mesic_partial_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "mesic_partial_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Mesic") %>% 
  mutate(treatment = "Partial") %>% 
  mutate(FEve = mesic_partial_fd$FEve) %>% 
  mutate(FDiv = mesic_partial_fd$FDiv) %>% 
  mutate(FDis = mesic_partial_fd$FDis) %>% 
  mutate(RaoQ = mesic_partial_fd$RaoQ)

FD_mesic_total <- as.data.frame(mesic_total_fd$FRic) %>% 
  rownames_to_column() %>% 
  rename(FRic = "mesic_total_fd$FRic") %>% 
  rename(Block = "rowname") %>% 
  mutate(climate = "Mesic") %>% 
  mutate(treatment = "Total")%>% 
  mutate(FEve = mesic_total_fd$FEve) %>% 
  mutate(FDiv = mesic_total_fd$FDiv) %>% 
  mutate(FDis = mesic_total_fd$FDis) %>% 
  mutate(RaoQ = mesic_total_fd$RaoQ)

FD_all <- rbind(FD_arid_open, FD_arid_partial, FD_arid_total, FD_int_open, FD_int_partial, FD_int_total, FD_mesic_open, FD_mesic_partial, FD_mesic_total)
```

```{r}
FD_all %>%
  pivot_longer(cols = c(FRic, FEve:FDis),
               names_to = "FD",
               values_to = "value") %>%
  ggplot(aes(x = climate, y = value, fill = climate, factor = treatment)) +
  scale_fill_manual(values = c("#f46d43", "#fee090", "#74add1")) +
  geom_boxplot() +
  theme_bw() +
  facet_wrap(~FD, scales = "free")

# ggsave("Functional_Diversity_Barchart.png", path = "~/github/Tejon_Functional_Traits/Figures")

```

```{r, include=FALSE}

# opts_knit$set(root.dir = "~/github/Tejon_Functional_Traits/Villeger_code/functions")

#loading Villeger functions
# setwd("~/github/Tejon_Functional_Traits/Villeger_code/functions") # folder where R functions have been saved

# source("quality_funct_space.R")
# source("plot_funct_space.R")
# source("multidimFD.R")
# source("multidimFbetaD.R")

```

```{r,include=FALSE}
# opts_knit$set(root.dir = "~/github/Tejon_Functional_Traits/Figures/FD")

# # make sure data is in correct format
# sum(row.names(arid_open_trait) %in% colnames(arid_open_abund)) == ncol(arid_open_abund) #TRUE
# 
# # first, use quality_funct_space(traits df, plot = "name")
# qual_funct_space <- quality_funct_space(arid_open_trait, 
#                                         plot = "arid_open_qual_funct_space")
# 
# qual_funct_space <- quality_funct_space(as.matrix(arid_open_trait), 
#                                         traits_weights = NULL, 
#                                         nbdim = 6, 
#                                         metric = "Gower",
#                                         dendro = TRUE, 
#                                         plot = "arid_open_qual_funct_space")
# 
# qual_funct_space$meanSD
# # best value is the smallest, so in this case 3D
# 
# arid_open_coord_3D <- qual_funct_space$details_funct_space$mat_coord[ ,1:3]
# arid_open_coord_3D
# 
# FD_test <- multidimFD(arid_open_coord_3D, 
#                          arid_open_abund, 
#                          check_species_pool = TRUE, 
#                          verb = TRUE,
#                          nm_asb_plot = row.names(arid_open_abund), 
#                          folder_plot = "~/github/Tejon_Functional_Traits/Figures/FD",
#                          Faxes_plot = colnames(arid_open_coord_3D)[1:3], 
#                          Faxes_nm_plot = colnames(arid_open_coord_3D)[1:3],
#                          plot_pool = TRUE, 
#                          col_bg = "grey90", 
#                          col_sp_pool = "grey30",  
#                          pch_sp_pool = "+", 
#                          cex_sp_pool = 1, 
#                          pch_sp = 21, 
#                          col_sp = "#1E90FF", 
#                          transp = 50)

```

### Models

#### FRic
    
```{r, warning=FALSE}
# interaction
FRic_1 <- glmmTMB(data = FD_all, FRic ~ climate * treatment + (1|Block), family = gaussian, na.action = na.fail)

# no interaction
FRic_2 <- glmmTMB(data = FD_all, FRic ~ climate + treatment + (1|Block), family = gaussian, na.action = na.fail)

# climate
FRic_3 <- glmmTMB(data = FD_all, FRic ~ climate + (1|Block), family = gaussian, na.action = na.fail)

# treatment
FRic_4 <- glmmTMB(data = FD_all, FRic ~ treatment + (1|Block), family = gaussian, na.action = na.fail)

# null
FRic_5 <- glmmTMB(data = FD_all, FRic ~ 1 + (1|Block), family = gaussian, na.action = na.fail)

AICc(FRic_1, FRic_2, FRic_3, FRic_4, FRic_5) # best model is null

simulateResiduals(FRic_5, plot = T) #ok? squiggly, but no warnings
shapiro.test(residuals(FRic_5)) # normal

```

#### FEve

```{r, warning=FALSE}
# interaction
FEve_1 <- glmmTMB(data = FD_all, FEve ~ climate * treatment + (1|Block), family = gaussian, na.action = na.fail)
dredge(FEve_1)
FEve_dredge <- dredge(FEve_1)

# no interaction
FEve_2 <- glmmTMB(data = FD_all, FEve ~ climate + treatment + (1|Block), family = gaussian, na.action = na.fail)

# climate
FEve_3 <- glmmTMB(data = FD_all, FEve ~ climate + (1|Block), family = gaussian, na.action = na.fail)

# treatment
FEve_4 <- glmmTMB(data = FD_all, FEve ~ treatment + (1|Block), family = gaussian, na.action = na.fail)

# null
FEve_5 <- glmmTMB(data = FD_all, FEve ~ 1 + (1|Block), family = gaussian, na.action = na.fail)

AICc(FEve_1, FEve_2, FEve_3, FEve_4, FEve_5) # best model is null? but followed closely by treatment

simulateResiduals(FEve_5, plot = T) # looks good
shapiro.test(residuals(FEve_5)) # normal

### model averaging
FEve_avg <- model.avg(get.models(FEve_dredge, subset = delta < 2)) # gets averaged coeffiients

FEve_sum <- summary(FEve_avg)
df_1 <- as.data.frame(FEve_sum$coefmat.full)

CI <- as.data.frame(confint(FEve_avg, full=T)) # get confidence intervals for full model

library(data.table)
df_1$CI.min <- CI$`2.5 %` #pulling out CIs and putting into same df as coefficient estimates
df_1$CI.max <- CI$`97.5 %`# order of coeffients same in both, so no mixups; but should check anyway
setDT(df_1, keep.rownames = "treatment") #put rownames into column
names(df_1) <- gsub(" ", "", names(df_1)) # remove spaces from column headers
df_1 <- df_1 %>% 
  mutate(treatment = ifelse(treatment == "cond((Int))", "Open",
                        ifelse(treatment == "cond(treatmentPartial)", "Partial", 
                               ifelse(treatment == "cond(treatmentTotal)", "Total", treatment))))
  

ggplot(data = df_1, aes(x = treatment, y = Estimate, color = treatment))+ 
  geom_point() + #points for coefficient estimates
  geom_errorbar(aes(ymin=CI.min, ymax=CI.max),
                width=.2,lwd=1) +
  scale_color_manual(values = c("gray30", "gray50", "gray80"))+
  theme(
    panel.background = element_rect(fill = "white",
                                    colour = "white",
                                    size = 0.5, linetype = "solid"),
    panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                    colour = "gray90"),
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                    colour = "gray90"),
    axis.line = element_line(size = 0.5, linetype = "solid",
                             colour = "gray85"),
    strip.background = element_rect(fill = "gray85"),
    strip.text = element_text(colour = 'gray20'))

emmeans(FEve_avg,  pairwise ~ treatment)

ref_grid(object = FEve_avg, data = FD_all)

```

#### FDiv

```{r, warning=FALSE}
# interaction
FDiv_1 <- glmmTMB(data = FD_all, FDiv ~ climate * treatment + (1|Block), family = gaussian, na.action = na.fail)

# no interaction
FDiv_2 <- glmmTMB(data = FD_all, FDiv ~ climate + treatment + (1|Block), family = gaussian, na.action = na.fail)

# climate
FDiv_3 <- glmmTMB(data = FD_all, FDiv ~ climate + (1|Block), family = gaussian, na.action = na.fail)

# treatment
FDiv_4 <- glmmTMB(data = FD_all, FDiv ~ treatment + (1|Block), family = gaussian, na.action = na.fail)

# null
FDiv_5 <- glmmTMB(data = FD_all, FDiv ~ 1 + (1|Block), family = gaussian, na.action = na.fail)

AICc(FDiv_1, FDiv_2, FDiv_3, FDiv_4, FDiv_5) #best model: FDiv ~ climate * treatment

simulateResiduals(FDiv_1, plot = T) # looks good
shapiro.test(residuals(FDiv_1)) # normal

# pairwise comparisons
emmeans(FDiv_1, pairwise ~ climate)
emmeans(FDiv_1, pairwise ~ treatment)
emmeans(FDiv_1, pairwise ~ climate * treatment)

# estimated marginal means plot
dat <- ggpredict(FDiv_1, terms = c("treatment", "climate"))
plot(dat, facet = TRUE)
dat <- ggpredict(FDiv_1, terms = c("climate", "treatment"))
plot(dat, facet = TRUE)

FDis_plot <- plot(ggpredict(FDis_5, terms = c("treatment", "climate")),  colors = ggeffects_colors, facet = TRUE)

```

#### FDis

```{r, warning=FALSE}
# interaction
FDis_1 <- glmmTMB(data = FD_all, FDis ~ climate * treatment + (1|Block), family = gaussian, na.action = na.fail)

# no interaction
FDis_2 <- glmmTMB(data = FD_all, FDis ~ climate + treatment + (1|Block), family = gaussian, na.action = na.fail)

# climate
FDis_3 <- glmmTMB(data = FD_all, FDis ~ climate + (1|Block), family = gaussian, na.action = na.fail)

# treatment
FDis_4 <- glmmTMB(data = FD_all, FDis ~ treatment + (1|Block), family = gaussian, na.action = na.fail)

# null
FDis_5 <- glmmTMB(data = FD_all, FDis ~ 1 + (1|Block), family = gaussian, na.action = na.fail)

AICc(FDis_1, FDis_2, FDis_3, FDis_4, FDis_5) #best model: FDis ~ climate * treatment

simulateResiduals(FDis_1, plot = T) # looks good
shapiro.test(residuals(FDis_1)) # normal

# pairwise comparisons
emmeans(FDis_1, pairwise ~ climate)
emmeans(FDis_1, pairwise ~ treatment)
emmeans(FDis_1, pairwise ~ climate * treatment)

# estimated marginal means plot
dat <- ggpredict(FDis_1, terms = c("treatment", "climate"))
plot(dat, facet = TRUE)

```

#### Best-Fit & AIC Table
```{r, include=FALSE}

# dredge_FRic <- as.data.frame(dredge(FRic)) %>%
#   filter(AICc == min(AICc)) %>% 
#   mutate(CWM = "FRic") %>% 
#   dplyr::select(CWM)
# 
# dredge_FEve <- as.data.frame(dredge(FEve)) %>%
#   filter(AICc == min(AICc)) %>% 
#   mutate(CWM = "FEve") %>%
#   dplyr::select(CWM)
# 
# dredge_FDiv <- as.data.frame(dredge(FDiv)) %>%
#   filter(AICc == min(AICc)) %>% 
#   mutate(CWM = "FDiv") %>%
#   dplyr::select(CWM, climate, treatment, "climate:treatment")
# 
# dredge_FDis <- as.data.frame(dredge(FDis)) %>%
#   filter(AICc == min(AICc)) %>% 
#   mutate(CWM = "FDis") %>%
#   dplyr::select(CWM, climate, treatment, "climate:treatment")
# 
# dredge_table <- dredge_FRic %>% 
#   full_join(dredge_FEve) %>% 
#   full_join(dredge_FDiv) %>% 
#   full_join(dredge_FDis) %>% 
#   mutate(climate = str_replace(climate, "\\+","x")) %>%
#   mutate(treatment = str_replace(treatment, "\\+","x")) %>% 
#   mutate(`climate:treatment` = str_replace(`climate:treatment`, "\\+","x"))
# 
# pretty_table <- dredge_table %>% 
#   as_tibble() %>% 
#   gt() %>% 
#   tab_header(
#     title = "FD Best-Fit Models"
#   ) %>% 
#   tab_spanner(
#     label = "Fixed Effects Terms",
#     columns = vars(climate, treatment, "climate:treatment")
#   ) %>% 
#   # fmt_number(
#   #   columns = vars(AICc),
#   #   decimals = 2
#   # ) %>% 
#   fmt_missing(
#     columns = vars(climate, treatment, "climate:treatment"),
#     missing_text = " "
#   ) %>% 
#   tab_source_note(
#     source_note = "x indicates selection of fixed effect term for best-fit model"
#   )
# 
# pretty_table
# 
# # gtsave(data = pretty_table, filename = "FD_Best_Fit_table.png", path = "~/github/Tejon_Functional_Traits/Figures")

```
#### AIC Supplement Table
```{r, include=FALSE}
# dredge_FRic <- as.data.frame(dredge(FRic)) %>%
#   mutate(CWM = "FRic") %>% 
#   dplyr::select(CWM, climate, treatment, "climate:treatment", AICc)
# 
# # dredge_FEve <- as.data.frame(dredge(FEve)) %>%
# #   mutate(CWM = "FEve") %>%
# #   dplyr::select(CWM, climate, treatment, "climate:treatment", AICc)
# 
# dredge_FDiv <- as.data.frame(dredge(FDiv)) %>%
#   mutate(CWM = "FDiv") %>%
#   dplyr::select(CWM, climate, treatment, "climate:treatment", AICc)
# 
# dredge_FDis <- as.data.frame(dredge(FDis)) %>%
#   mutate(CWM = "FDis") %>%
#   dplyr::select(CWM, climate, treatment, "climate:treatment", AICc)
# 
# dredge_table <- dredge_FRic %>% 
#   full_join(dredge_FEve) %>% 
#   full_join(dredge_FDiv) %>% 
#   full_join(dredge_FDis) %>% 
#   mutate(climate = str_replace(climate, "\\+","x")) %>%
#   mutate(treatment = str_replace(treatment, "\\+","x")) %>% 
#   mutate(`climate:treatment` = str_replace(`climate:treatment`, "\\+","x"))
# dredge_table
# 
# fd_aic_sup <- dredge_table %>% 
#   as_tibble() %>% 
#   dplyr::group_by(CWM) %>%
#   gt() %>% 
#   tab_header(
#     title = "FD Best-Fit Models"
#   ) %>% 
#   tab_spanner(
#     label = "Fixed Effects Terms",
#     columns = vars(climate, treatment, "climate:treatment")
#   ) %>% 
#   fmt_missing(
#     columns = vars(climate, treatment, "climate:treatment"),
#     missing_text = " "
#   ) %>% 
#   tab_source_note(
#     source_note = "x indicates selection of fixed effect term for best-fit model"
#   )  %>% 
#   cols_align(align = "center")
# 
# fd_aic_sup

# gtsave(data = fd_aic_sup, filename = "FD_AIC_Supp.png", path = "~/github/Tejon_Functional_Traits/Figures")

```
#### emmeans graphs
```{r, include=FALSE}
#### EMM Graphs

# color of arrows
arrow_colors <- (rep(c("red", "orange", "blue"), 3))

# significance caption
symbol <- "\u2264"
caption <- paste0(symbol, "0.05(*), ", symbol, "0.01()**, ", symbol, "0.001(***)")

emm_plot <- function(emmeans) {
  plot(emmeans, by = NULL, CIs = FALSE, comparisons = TRUE, horizontal = FALSE, colors = "darkgreen") +
  # facet_grid by climate, and remove empty values
  # facet_grid(. ~climate, scales = "free", space = "free") +
  labs(y = "EMM", x = "Climate") +
  aes(fill = as.factor(treatment)) +
  # changing color of comparison arrow lines
  geom_segment(aes_(y = ~the.emmean, yend = ~lcmpl, x = ~pri.fac, xend = ~pri.fac), #copied from function's code on github
               arrow = arrow(length = ggplot2::unit(.07, "inches"), type = "closed"),
               color = arrow_colors) +
  geom_segment(ggplot2::aes_(y = ~the.emmean, yend = ~rcmpl, x = ~pri.fac, xend = ~pri.fac),
               arrow = arrow(length = ggplot2::unit(.07, "inches"), type = "closed"),
               color = arrow_colors) +
  # changing color of point
  geom_point(aes_(fill = "black")) +
  # changing theme
  theme_bw() +
  # removing legend
  theme(legend.position = "none") +
  # changing x labels within facet_grid
  scale_x_discrete(labels = c("Open", "Partial", "Total", "Open", "Partial", "Total", "Open", "Partial", "Total")) +
  # transparent background
  theme(panel.background = element_rect(fill = "transparent"), plot.background = element_rect(fill = "transparent", color = NA)) +
  # adding footnote
  labs(caption = caption)
}

# FRic
FRic_emmeans <- emmeans(FRic, ~ treatment | climate)
# emmeans(FRic, pairwise ~ treatment | climate)
FRic_plot <- emm_plot(FRic_emmeans) +
  labs(title = "Functional Richness") +
  # Arid-Open - Arid-Partial
  geom_signif(annotation = "***",
    y_position = 7.25, xmin = 1, xmax = 2,
    tip_length = c(.7, .025)) +
  # Arid-Partial - Arid-Total
  geom_signif(annotation = "**",
    y_position = 7.75, xmin = 2, xmax = 3,
    tip_length = c(.05, .5)) +
  # Mesic-Open - Mesic-Partial
   geom_signif(annotation = "*",
    y_position = 7.2, xmin = 7, xmax = 8,
    tip_length = c(.05, .3)) +
    # Mesic-Open - Mesic-Total
   geom_signif(annotation = "**",
    y_position = 5, xmin = 8, xmax = 9,
    tip_length = c(.05, .2))

# ggsave("FRic_emmean.png", plot = FRic_plot, path = "~/github/Tejon_Functional_Traits/Figures", height = 4, width = 5, bg = "transparent")

# FDiv
FDiv_emmeans <- emmeans(FDiv, ~ treatment | climate)
# emmeans(FDiv, pairwise ~ treatment | climate)
FDiv_plot <- emm_plot(FDiv_emmeans) +
  labs(title = "Functional Divergence") +
  # Arid-Open - Arid-Partial
  geom_signif(annotation = "***",
    y_position = .8, xmin = 1, xmax = 2,
    tip_length = c(.05, .5)) +
  # Arid-Open - Arid-Total
  geom_signif(annotation = "*",
    y_position = 1.05, xmin = 1, xmax = 3,
    tip_length = c(.4, .1)) +
  # Arid-Partial - Arid-Total
  geom_signif(annotation = "***",
    y_position = .95, xmin = 2, xmax = 3,
    tip_length = c(.05, .05)) +
  # Int all
  geom_signif(annotation = "***",
    y_position = .8, xmin = 4, xmax = 5,
    tip_length = c(.05, .5)) +
  geom_signif(annotation = "***",
    y_position = .95, xmin = 5, xmax = 6,
    tip_length = c(.05, .05)) +
  geom_signif(annotation = "***",
    y_position = 1.05, xmin = 4, xmax = 6,
    tip_length = c(.4, .1)) +
  # Mesic-Partial - Mesic-Total
  geom_signif(annotation = "*",
    y_position = .9, xmin = 8, xmax = 9,
    tip_length = c(.3, .05))

# ggsave("FDiv_emmean.png", plot = FDiv_plot, path = "~/github/Tejon_Functional_Traits/Figures", height = 4, width = 5, bg = "transparent")

# FDis
FDis_emmeans <- emmeans(FDis_1, ~ treatment | climate)
# emmeans(FDis, pairwise ~ treatment | climate)
FDis_plot <- emm_plot(FDis_emmeans) +
  labs(title = "Functional Dispersion") +
  # Arid-Open - Arid-Total
  geom_signif(annotation = "***",
    y_position = 1.5, xmin = 1, xmax = 3,
    tip_length = c(.5, .05)) +
    # Arid-Partial - Arid-Total
  geom_signif(annotation = "**",
    y_position = 1.4, xmin = 2, xmax = 3,
    tip_length = c(.3, .05)) +
  # Int-Open - Int-Total
   geom_signif(annotation = "***",
    y_position = 1.9, xmin = 4, xmax = 6,
    tip_length = c(.85, .05)) +
  # Int-Partial - Int-Total
   geom_signif(annotation = "***",
    y_position = 1.8, xmin = 5, xmax = 6,
    tip_length = c(.8, .05)) +
  # Mesic-Open - Mesic-Partial
  geom_signif(annotation = "**",
    y_position = 1.7, xmin = 7, xmax = 8,
    tip_length = c(.05, .3)) +
  # Mesic-Open - Mesic-Total
  geom_signif(annotation = "*",
    y_position = 1.8, xmin = 7, xmax = 9,
    tip_length = c(.05, .35))

FDis_plot

# ggsave("FDis_emmean.png", plot = FDis_plot, path = "~/github/Tejon_Functional_Traits/Figures", height = 4, width = 5, bg = "transparent")

```

#### ggeffects graphs
```{r, include=FALSE}

# ggeffects Graphs

ggeffects_colors <- c("#f46d43", "#fee090", "#74add1")

FDis_plot <- plot(ggpredict(FDis_5, terms = c("treatment", "climate")),  colors = ggeffects_colors, facet = TRUE)

ggpredict(FDis_5, terms = c("treatment", "climate"))

# FEve_plot <- plot(ggpredict(FEve),  colors = ggeffects_colors, facet = TRUE)

FDiv_plot <- plot(ggpredict(FDiv_5, terms = c("treatment", "climate")),  colors = ggeffects_colors, facet = TRUE)

FD_emmeans <- grid.arrange(FRic_plot, FDiv_plot)

ggsave("CFD_emmeans.png", plot = FD_emmeans, path = "~/github/Tejon_Functional_Traits/Figures/ggeffects_graphs", height = 7, width = 5)

```

```{r}

graphs <- function(model_name, model_terms, plot_title, y_label, y_positions = 20) {
  # model_name ex: LDMC_CWM
  # model_terms as a list ex: c("treatment", "climate")
  # model_formula ex: "pairwise ~ climate * treatment"
  
  predict <- ggpredict(model_name, terms = model_terms)
  test <- as.data.frame(predict)
  
  # creating annotation data frame that will be used by geom_signif to get around the facet_wrap() problem
  anno <- as.data.frame(summary(emmeans(model_name, specs = pairwise ~ climate * treatment))$contrasts) %>% 
      filter(p.value <= 0.05) %>%
    separate(col = contrast, into = c("plot_1", "plot_2"), sep = " - ") %>%
    separate(col = plot_1, into = c("plot_1_climate", "plot_1_treatment"), sep = " ") %>%
    separate(col = plot_2, into = c("plot_2_climate", "plot_2_treatment"), sep = " ") %>%
    filter(plot_1_climate == plot_2_climate) %>%
    rename(group = plot_1_climate, start = plot_1_treatment, end = plot_2_treatment) %>%
    mutate(label = ifelse(p.value > .05, "*",
                        ifelse(p.value <= 0.01, "**",
                               ifelse(p.value <= 0.001, "***", "****")))) %>%
    dplyr::select(group, start, end, label)

  print(anno)
  
  ggplot(test, aes(x, predicted, color = group)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = .25, size = .75) +
  scale_color_manual(values = ggeffects_colors) +
  theme(
    panel.background = element_rect(fill = "white",
                                    colour = "white",
                                    size = 0.5, linetype = "solid"),
    panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                    colour = "gray90"),
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                    colour = "gray90"),
    axis.line = element_line(size = 0.5, linetype = "solid",
                             colour = "gray85"),
    strip.background = element_rect(fill = "gray85"),
    strip.text = element_text(colour = 'gray20')
  ) +
    labs(title = plot_title, y = y_label, x = "Herbivore Treatment") +
    geom_signif(
      data = anno,
      aes(xmin = start, xmax = end, annotations = label, y_position = y_positions),
      color = "black",
      manual = TRUE) +
    facet_grid(~group)+
    theme(legend.position = "none")
}

FDiv_plot <- graphs(model_name = FDiv_1,
       model_terms = c("treatment", "climate"),
       plot_title = "Functional Divergence (FDiv)",
       y_label = "FDiv",
       y_positions = c(.75, 1.1, 1)) +
  expand_limits(y = 1.2)

FDiv_plot

FDis_plot <- graphs(model_name = FDis_1,
       model_terms = c("treatment", "climate"),
       plot_title = "Functional Dispersion (FDis)",
       y_label = "FDis",
       y_positions = c(1.6, 1.75, 1.95, 1.85))+
  expand_limits(y = 2.1)

FDis_plot

FD_signif_all <- grid.arrange(FDiv_plot, FDis_plot)

ggsave("FD_ggeffects.png", plot = FD_signif_all, path = "~/github/Tejon_Functional_Traits/Figures/ggeffects_graphs", height = 7, width = 5)
```

